### PR TITLE
Event warrior id bug 43

### PR DESCRIPTION
**Pull request by gareththegeek**
Fix for #43

### CODE REVIEW

**Comment by gareththegeek** [comment]
It's as I thought all along, the problem is unsolveable

**Comment by dougajmcdonald** [comment]
I'm seeing that problem locally

**Comment by gareththegeek** [comment]
I thought the problem was that I checked in the local path version of the package.json but then reverted it so it's weird you're seeing the same

**Comment by dougajmcdonald** [comment]
Fixed...I'm a magician!

**Comment by gareththegeek** [comment]
This f**ker is a magician too!1one?

**Comment by dougajmcdonald** [comment]
It was `clone` missing from the corewar npm package btw, in case you were interested...told you we should have used `Object.assign()` ;-)

**Pull request merged**
